sudo: required
services:
  - docker
before_install:
  - docker pull nimlang/nim
script:
  - docker run nimlang/nim nim --version
  - docker run -v "$(pwd):/project" -w /project nimlang/nim sh -c "nimble build -y"
  - docker run -v "$(pwd):/project" -w /project nimlang/nim sh -c "nim c -p=. tests/test_functional.nim"
  - docker run -v "$(pwd):/project" -w /project nimlang/nim sh -c "SHOWOUT=1 ./tests/test_functional"
