version: 2
jobs:
  build:
    docker:
      - image: debian:stable
    steps:
      - run:
          name: install dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get install -y --no-install-recommends git ssh ca-certificates
      - run: git clone https://github.com/FedericoCeratto/nim-package-directory.git
      - run:
          name: install dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            #apt-get build-dep -y .
            apt-get install -y --no-install-recommends build-essential git ssh
      # Reuse cached Nim compiler
      - restore_cache:
          key: compiler-0002
      - run:
          command: |
            apt-get install -y nim
      - save_cache:
          key: compiler-0002
          paths:
            - ~/.nimble
            - ~/.choosenim
      - run:
          name: run Debian build
          command: DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -us -uc -b -j4

